# Generated by Django 3.1.6 on 2021-02-17 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wavepool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
